import { Injectable } from '@angular/core';

import { Departamento } from '../models/departamento.model';
import { Ciudad } from '../models/ciudad.model';

@Injectable({
  providedIn: 'root',
})

export class DepartamentService {
  private d: Departamento[] = [];

  constructor() {
    this.d.push(new Departamento('63', 'QUINDIO'));
    this.d.push(new Departamento('66', 'RISARALDA'));
    this.d.push(new Departamento('17', 'CALDAS'));
    this.d.push(new Departamento('5', 'ANTIOQUIA'));
    this.d.push(new Departamento('8', 'ATLANTICO'));
    this.d.push(new Departamento('11', 'SANTAFE DE BOGOTA'));
    this.d.push(new Departamento('13', 'BOLIVAR'));
    this.d.push(new Departamento('15', 'BOYACA'));
    this.d.push(new Departamento('18', 'CAQUETA'));
    this.d.push(new Departamento('19', 'CAUCA'));
    this.d.push(new Departamento('20', 'CESAR'));
    this.d.push(new Departamento('23', 'CORDOBA'));
    this.d.push(new Departamento('25', 'CUNDINAMARCA'));
    this.d.push(new Departamento('27', 'CHOCO'));
    this.d.push(new Departamento('41', 'HUILA'));
    this.d.push(new Departamento('44', 'LA GUAJIRA'));
    this.d.push(new Departamento('47', 'MAGDALENA'));
    this.d.push(new Departamento('50', 'META'));
    this.d.push(new Departamento('52', 'NARIÑO'));
    this.d.push(new Departamento('54', 'NORTE DE SANTANDER'));
    this.d.push(new Departamento('68', 'SANTANDER'));
    this.d.push(new Departamento('70', 'SUCRE'));
    this.d.push(new Departamento('73', 'TOLIMA'));
    this.d.push(new Departamento('76', 'VALLE DEL CAUCA'));
    this.d.push(new Departamento('81', 'ARAUCA'));
    this.d.push(new Departamento('85', 'CASANARE'));
    this.d.push(new Departamento('86', 'PUTUMAYO'));
    this.d.push(new Departamento('88', 'ARCHIPIELAGO DE SAN ANDRES'));
    this.d.push(new Departamento('91', 'AMAZONAS'));
    this.d.push(new Departamento('94', 'GUAINIA'));
    this.d.push(new Departamento('95', 'GUAVIARE'));
    this.d.push(new Departamento('97', 'VAUPES'));
    this.d.push(new Departamento('99', 'VICHADA'));
  }

  getDepartamentos(): Departamento[] {
    return this.d;
  }
  getCiudades(nombredepto: string): Ciudad[] {
    let c: Ciudad[] = [];

    const departamento = this.d.find((departamento) => departamento.nombre === nombredepto);

    switch (departamento.cod) {
      case '5':
        c.push(new Ciudad('1', 'MEDELLIN'));
        c.push(new Ciudad('2', 'ABEJORRAL'));
        c.push(new Ciudad('4', 'ABRIAQUI'));
        c.push(new Ciudad('21', 'ALEJANDRIA'));
        c.push(new Ciudad('30', 'AMAGA'));
        c.push(new Ciudad('31', 'AMALFI'));
        c.push(new Ciudad('34', 'ANDES'));
        c.push(new Ciudad('36', 'ANGELOPOLIS'));
        c.push(new Ciudad('38', 'ANGOSTURA'));
        c.push(new Ciudad('40', 'ANORI'));
        c.push(new Ciudad('42', 'SANTAFE DE ANTIOQUIA'));
        c.push(new Ciudad('44', 'ANZA'));
        c.push(new Ciudad('45', 'APARTADO'));
        c.push(new Ciudad('51', 'ARBOLETES'));
        c.push(new Ciudad('55', 'ARGELIA'));
        c.push(new Ciudad('59', 'ARMENIA'));
        c.push(new Ciudad('79', 'BARBOSA'));
        c.push(new Ciudad('86', 'BELMIRA'));
        c.push(new Ciudad('88', 'BELLO'));
        c.push(new Ciudad('91', 'BETANIA'));
        c.push(new Ciudad('93', 'BETULIA'));
        c.push(new Ciudad('101', 'CIUDAD BOLIVAR'));
        c.push(new Ciudad('107', 'BRICEÑO'));
        c.push(new Ciudad('113', 'BURITICA'));
        c.push(new Ciudad('120', 'CACERES'));
        c.push(new Ciudad('125', 'CAICEDO'));
        c.push(new Ciudad('129', 'CALDAS'));
        c.push(new Ciudad('134', 'CAMPAMENTO'));
        c.push(new Ciudad('138', 'CAÑAS GORDAS'));
        c.push(new Ciudad('142', 'CARACOLI'));
        c.push(new Ciudad('145', 'CARAMANTA'));
        c.push(new Ciudad('147', 'CAREPA'));
        c.push(new Ciudad('148', 'CARMEN DE VIBORAL'));
        c.push(new Ciudad('150', 'CAROLINA'));
        c.push(new Ciudad('154', 'CAUCASIA'));
        c.push(new Ciudad('172', 'CHIGORODO'));
        c.push(new Ciudad('190', 'CISNEROS'));
        c.push(new Ciudad('197', 'COCORNA'));
        c.push(new Ciudad('206', 'CONCEPCION'));
        c.push(new Ciudad('209', 'CONCORDIA'));
        c.push(new Ciudad('212', 'COPACABANA'));
        c.push(new Ciudad('234', 'DABEIBA'));
        c.push(new Ciudad('237', 'DON MATIAS'));
        c.push(new Ciudad('240', 'EBEJICO'));
        c.push(new Ciudad('250', 'EL BAGRE'));
        c.push(new Ciudad('264', 'ENTRERRIOS'));
        c.push(new Ciudad('266', 'ENVIGADO'));
        c.push(new Ciudad('282', 'FREDONIA'));
        c.push(new Ciudad('284', 'FRONTINO'));
        c.push(new Ciudad('306', 'GIRALDO'));
        c.push(new Ciudad('308', 'GIRARDOTA'));
        c.push(new Ciudad('310', 'GOMEZ PLATA'));
        c.push(new Ciudad('313', 'GRANADA'));
        c.push(new Ciudad('315', 'GUADALUPE'));
        c.push(new Ciudad('318', 'GUARNE'));
        c.push(new Ciudad('321', 'GUATAPE'));
        c.push(new Ciudad('347', 'HELICONIA'));
        c.push(new Ciudad('353', 'HISPANIA'));
        c.push(new Ciudad('360', 'ITAGUI'));
        c.push(new Ciudad('361', 'ITUANGO'));
        c.push(new Ciudad('364', 'JARDIN'));
        c.push(new Ciudad('368', 'JERICO'));
        c.push(new Ciudad('376', 'LA CEJA'));
        c.push(new Ciudad('380', 'LA ESTRELLA'));
        c.push(new Ciudad('390', 'La Pintada'));
        c.push(new Ciudad('400', 'LA UNION'));
        c.push(new Ciudad('411', 'LIBORINA'));
        c.push(new Ciudad('425', 'MACEO'));
        c.push(new Ciudad('440', 'MARINILLA'));
        c.push(new Ciudad('467', 'MONTEBELLO'));
        c.push(new Ciudad('475', 'MURINDO'));
        c.push(new Ciudad('480', 'MUTATA'));
        c.push(new Ciudad('483', 'NARIÑO'));
        c.push(new Ciudad('490', 'NECOCLI'));
        c.push(new Ciudad('495', 'NECHI'));
        c.push(new Ciudad('501', 'OLAYA'));
        c.push(new Ciudad('541', 'PEÑOL'));
        c.push(new Ciudad('543', 'PEQUE'));
        c.push(new Ciudad('576', 'PUEBLORRICO'));
        c.push(new Ciudad('579', 'PUERTO BERRIO'));
        c.push(new Ciudad('585', 'PUERTO NARE'));
        c.push(new Ciudad('591', 'PUERTO TRIUNFO'));
        c.push(new Ciudad('604', 'REMEDIOS'));
        c.push(new Ciudad('607', 'RETIRO'));
        c.push(new Ciudad('615', 'RIONEGRO'));
        c.push(new Ciudad('628', 'SABANALARGA'));
        c.push(new Ciudad('631', 'SABANETA'));
        c.push(new Ciudad('642', 'SALGAR'));
        c.push(new Ciudad('647', 'SAN ANDRES'));
        c.push(new Ciudad('649', 'SAN CARLOS'));
        c.push(new Ciudad('652', 'SAN FRANCISCO'));
        c.push(new Ciudad('656', 'SAN JERONIMO'));
        c.push(new Ciudad('658', 'SAN JOSE DE LA MONTAÑA'));
        c.push(new Ciudad('659', 'SAN JUAN DE URABA'));
        c.push(new Ciudad('660', 'SAN LUIS'));
        c.push(new Ciudad('664', 'SAN PEDRO'));
        c.push(new Ciudad('665', 'SAN PEDRO DE URABA'));
        c.push(new Ciudad('667', 'SAN RAFAEL'));
        c.push(new Ciudad('670', 'SAN ROQUE'));
        c.push(new Ciudad('674', 'SAN VICENTE'));
        c.push(new Ciudad('679', 'SANTA BARBARA'));
        c.push(new Ciudad('686', 'SANTA ROSA DE OSOS'));
        c.push(new Ciudad('690', 'SANTO DOMINGO'));
        c.push(new Ciudad('697', 'SANTUARIO'));
        c.push(new Ciudad('736', 'SEGOVIA'));
        c.push(new Ciudad('756', 'SONSON'));
        c.push(new Ciudad('761', 'SOPETRAN'));
        c.push(new Ciudad('789', 'TAMESIS'));
        c.push(new Ciudad('790', 'TARAZA'));
        c.push(new Ciudad('792', 'TARSO'));
        c.push(new Ciudad('809', 'TITIRIBI'));
        c.push(new Ciudad('819', 'TOLEDO'));
        c.push(new Ciudad('837', 'TURBO'));
        c.push(new Ciudad('842', 'URAMITA'));
        c.push(new Ciudad('847', 'URRAO'));
        c.push(new Ciudad('854', 'VALDIVIA'));
        c.push(new Ciudad('856', 'VALPARAISO'));
        c.push(new Ciudad('858', 'VEGACHI'));
        c.push(new Ciudad('861', 'VENECIA'));
        c.push(new Ciudad('873', 'VIGIA DEL FUERTE'));
        c.push(new Ciudad('885', 'YALI'));
        c.push(new Ciudad('887', 'YARUMAL'));
        c.push(new Ciudad('890', 'YOLOMBO'));
        c.push(new Ciudad('893', 'YONDO'));
        c.push(new Ciudad('895', 'ZARAGOZA'));
        break;
      case '8':
        c.push(new Ciudad('1', 'BARRANQUILLA'));
        c.push(new Ciudad('78', 'BARANOA'));
        c.push(new Ciudad('137', 'CAMPO DE LA CRUZ'));
        c.push(new Ciudad('141', 'CANDELARIA'));
        c.push(new Ciudad('296', 'GALAPA'));
        c.push(new Ciudad('372', 'JUAN DE ACOSTA'));
        c.push(new Ciudad('421', 'LURUACO'));
        c.push(new Ciudad('433', 'MALAMBO'));
        c.push(new Ciudad('436', 'MANATI'));
        c.push(new Ciudad('520', 'PALMAR DE VARELA'));
        c.push(new Ciudad('549', 'PIOJO'));
        c.push(new Ciudad('558', 'POLONUEVO'));
        c.push(new Ciudad('560', 'PONEDERA'));
        c.push(new Ciudad('573', 'PUERTO COLOMBIA'));
        c.push(new Ciudad('606', 'REPELON'));
        c.push(new Ciudad('634', 'SABANAGRANDE'));
        c.push(new Ciudad('638', 'SABANALARGA'));
        c.push(new Ciudad('675', 'SANTA LUCIA'));
        c.push(new Ciudad('685', 'SANTO TOMAS'));
        c.push(new Ciudad('758', 'SOLEDAD'));
        c.push(new Ciudad('770', 'SUAN'));
        c.push(new Ciudad('832', 'TUBARA'));
        c.push(new Ciudad('849', 'USIACURI'));
        break;
      case '11':
        c.push(new Ciudad('1', 'BOGOTA D.C.'));
        break;
      case '13':
        c.push(new Ciudad('1', 'CARTAGENA'));
        c.push(new Ciudad('6', 'ACHI'));
        c.push(new Ciudad('30', 'ALTOS DEL ROSARIO'));
        c.push(new Ciudad('42', 'ARENAL'));
        c.push(new Ciudad('52', 'ARJONA'));
        c.push(new Ciudad('62', 'Arroyohondo'));
        c.push(new Ciudad('74', 'BARRANCO DE LOBA'));
        c.push(new Ciudad('140', 'CALAMAR'));
        c.push(new Ciudad('160', 'CANTAGALLO'));
        c.push(new Ciudad('188', 'CICUCO'));
        c.push(new Ciudad('212', 'CORDOBA'));
        c.push(new Ciudad('222', 'CLEMENCIA'));
        c.push(new Ciudad('244', 'EL CARMEN DE BOLIVAR'));
        c.push(new Ciudad('248', 'EL GUAMO'));
        c.push(new Ciudad('268', 'EL PEÑON'));
        c.push(new Ciudad('300', 'HATILLO DE LOBA'));
        c.push(new Ciudad('430', 'MAGANGUE'));
        c.push(new Ciudad('433', 'MAHATES'));
        c.push(new Ciudad('440', 'MARGARITA'));
        c.push(new Ciudad('442', 'MARIA LA BAJA'));
        c.push(new Ciudad('458', 'MONTECRISTO'));
        c.push(new Ciudad('468', 'MOMPOS'));
        c.push(new Ciudad('473', 'MORALES'));
        c.push(new Ciudad('490', 'Norosi'));
        c.push(new Ciudad('549', 'PINILLOS'));
        c.push(new Ciudad('580', 'REGIDOR'));
        c.push(new Ciudad('600', 'RIO VIEJO'));
        c.push(new Ciudad('620', 'SAN CRISTOBAL'));
        c.push(new Ciudad('647', 'SAN ESTANISLAO'));
        c.push(new Ciudad('650', 'SAN FERNANDO'));
        c.push(new Ciudad('654', 'SAN JACINTO'));
        c.push(new Ciudad('655', 'San Jacinto del Cauca'));
        c.push(new Ciudad('657', 'SAN JUAN NEPOMUCENO'));
        c.push(new Ciudad('667', 'SAN MARTIN DE LOBA'));
        c.push(new Ciudad('670', 'SAN PABLO'));
        c.push(new Ciudad('673', 'SANTA CATALINA'));
        c.push(new Ciudad('683', 'SANTA ROSA'));
        c.push(new Ciudad('688', 'SANTA ROSA DEL SUR'));
        c.push(new Ciudad('744', 'SIMITI'));
        c.push(new Ciudad('760', 'SOPLAVIENTO'));
        c.push(new Ciudad('780', 'TALAIGUA NUEVO'));
        c.push(new Ciudad('810', 'TIQUISIO'));
        c.push(new Ciudad('836', 'TURBACO'));
        c.push(new Ciudad('838', 'TURBANA'));
        c.push(new Ciudad('873', 'VILLANUEVA'));
        c.push(new Ciudad('894', 'ZAMBRANO'));
        break;
      case '1':
        c.push(new Ciudad('1', 'TUNJA'));
        c.push(new Ciudad('22', 'ALMEIDA'));
        c.push(new Ciudad('47', 'AQUITANIA'));
        c.push(new Ciudad('51', 'ARCABUCO'));
        c.push(new Ciudad('87', 'BELEN'));
        c.push(new Ciudad('90', 'BERBEO'));
        c.push(new Ciudad('92', 'BETEITIVA'));
        c.push(new Ciudad('97', 'BOAVITA'));
        c.push(new Ciudad('104', 'BOYACA'));
        c.push(new Ciudad('106', 'BRICEÑO'));
        c.push(new Ciudad('109', 'BUENAVISTA'));
        c.push(new Ciudad('114', 'BUSBANZA'));
        c.push(new Ciudad('131', 'CALDAS'));
        c.push(new Ciudad('135', 'CAMPOHERMOSO'));
        c.push(new Ciudad('162', 'CERINZA'));
        c.push(new Ciudad('172', 'CHINAVITA'));
        c.push(new Ciudad('176', 'CHIQUINQUIRA'));
        c.push(new Ciudad('180', 'CHISCAS'));
        c.push(new Ciudad('183', 'CHITA'));
        c.push(new Ciudad('185', 'CHITARAQUE'));
        c.push(new Ciudad('187', 'CHIVATA'));
        c.push(new Ciudad('189', 'CIENEGA'));
        c.push(new Ciudad('204', 'COMBITA'));
        c.push(new Ciudad('212', 'COPER'));
        c.push(new Ciudad('215', 'CORRALES'));
        c.push(new Ciudad('218', 'COVARACHIA'));
        c.push(new Ciudad('223', 'CUBARA'));
        c.push(new Ciudad('224', 'CUCAITA'));
        c.push(new Ciudad('226', 'CUITIVA'));
        c.push(new Ciudad('232', 'CHIQUIZA'));
        c.push(new Ciudad('236', 'CHIVOR'));
        c.push(new Ciudad('238', 'DUITAMA'));
        c.push(new Ciudad('244', 'EL COCUY'));
        c.push(new Ciudad('248', 'EL ESPINO'));
        c.push(new Ciudad('272', 'FIRAVITOBA'));
        c.push(new Ciudad('276', 'FLORESTA'));
        c.push(new Ciudad('293', 'GACHANTIVA'));
        c.push(new Ciudad('296', 'GAMEZA'));
        c.push(new Ciudad('299', 'GARAGOA'));
        c.push(new Ciudad('317', 'GUACAMAYAS'));
        c.push(new Ciudad('322', 'GUATEQUE'));
        c.push(new Ciudad('325', 'GUAYATA'));
        c.push(new Ciudad('332', 'GUICAN'));
        c.push(new Ciudad('362', 'IZA'));
        c.push(new Ciudad('367', 'JENESANO'));
        c.push(new Ciudad('368', 'JERICO'));
        c.push(new Ciudad('377', 'LABRANZAGRANDE'));
        c.push(new Ciudad('380', 'LA CAPILLA'));
        c.push(new Ciudad('401', 'LA VICTORIA'));
        c.push(new Ciudad('403', 'LA UVITA'));
        c.push(new Ciudad('407', 'VILLA DE LEYVA'));
        c.push(new Ciudad('425', 'MACANAL'));
        c.push(new Ciudad('442', 'MARIPI'));
        c.push(new Ciudad('455', 'MIRAFLORES'));
        c.push(new Ciudad('464', 'MONGUA'));
        c.push(new Ciudad('466', 'MONGUI'));
        c.push(new Ciudad('469', 'MONIQUIRA'));
        c.push(new Ciudad('476', 'MOTAVITA'));
        c.push(new Ciudad('480', 'MUZO'));
        c.push(new Ciudad('491', 'NOBSA'));
        c.push(new Ciudad('494', 'NUEVO COLON'));
        c.push(new Ciudad('500', 'OICATA'));
        c.push(new Ciudad('507', 'OTANCHE'));
        c.push(new Ciudad('511', 'PACHAVITA'));
        c.push(new Ciudad('514', 'PAEZ'));
        c.push(new Ciudad('516', 'PAIPA'));
        c.push(new Ciudad('518', 'PAJARITO'));
        c.push(new Ciudad('522', 'PANQUEBA'));
        c.push(new Ciudad('531', 'PAUNA'));
        c.push(new Ciudad('533', 'PAYA'));
        c.push(new Ciudad('537', 'PAZ DE RIO'));
        c.push(new Ciudad('542', 'PESCA'));
        c.push(new Ciudad('550', 'PISBA'));
        c.push(new Ciudad('572', 'PUERTO BOYACA'));
        c.push(new Ciudad('580', 'QUIPAMA'));
        c.push(new Ciudad('599', 'RAMIRIQUI'));
        c.push(new Ciudad('600', 'RAQUIRA'));
        c.push(new Ciudad('621', 'RONDON'));
        c.push(new Ciudad('632', 'SABOYA'));
        c.push(new Ciudad('638', 'SACHICA'));
        c.push(new Ciudad('646', 'SAMACA'));
        c.push(new Ciudad('660', 'SAN EDUARDO'));
        c.push(new Ciudad('664', 'SAN JOSE DE PARE'));
        c.push(new Ciudad('667', 'SAN LUIS DE GACENO'));
        c.push(new Ciudad('673', 'SAN MATEO'));
        c.push(new Ciudad('676', 'SAN MIGUEL DE SEMA'));
        c.push(new Ciudad('681', 'SAN PABLO BORBUR'));
        c.push(new Ciudad('686', 'SANTANA'));
        c.push(new Ciudad('690', 'SANTA MARIA'));
        c.push(new Ciudad('693', 'SAN ROSA VITERBO'));
        c.push(new Ciudad('696', 'SANTA SOFIA'));
        c.push(new Ciudad('720', 'SATIVANORTE'));
        c.push(new Ciudad('723', 'SATIVASUR'));
        c.push(new Ciudad('740', 'SIACHOQUE'));
        c.push(new Ciudad('753', 'SOATA'));
        c.push(new Ciudad('755', 'SOCOTA'));
        c.push(new Ciudad('757', 'SOCHA'));
        c.push(new Ciudad('759', 'SOGAMOSO'));
        c.push(new Ciudad('761', 'SOMONDOCO'));
        c.push(new Ciudad('762', 'SORA'));
        c.push(new Ciudad('763', 'SOTAQUIRA'));
        c.push(new Ciudad('764', 'SORACA'));
        c.push(new Ciudad('774', 'SUSACON'));
        c.push(new Ciudad('776', 'SUTAMARCHAN'));
        c.push(new Ciudad('778', 'SUTATENZA'));
        c.push(new Ciudad('790', 'TASCO'));
        c.push(new Ciudad('798', 'TENZA'));
        c.push(new Ciudad('804', 'TIBANA'));
        c.push(new Ciudad('806', 'TIBASOSA'));
        c.push(new Ciudad('808', 'TINJACA'));
        c.push(new Ciudad('810', 'TIPACOQUE'));
        c.push(new Ciudad('814', 'TOCA'));
        c.push(new Ciudad('816', 'TOGUI'));
        c.push(new Ciudad('820', 'TOPAGA'));
        c.push(new Ciudad('822', 'TOTA'));
        c.push(new Ciudad('832', 'TUNUNGUA'));
        c.push(new Ciudad('835', 'TURMEQUE'));
        c.push(new Ciudad('837', 'TUTA'));
        c.push(new Ciudad('839', 'TUTAZA'));
        c.push(new Ciudad('842', 'UMBITA'));
        c.push(new Ciudad('861', 'VENTAQUEMADA'));
        c.push(new Ciudad('879', 'VIRACACHA'));
        c.push(new Ciudad('897', 'ZETAQUIRA'));
        break;
      case '17':
        c.push(new Ciudad('1', 'MANIZALES'));
        c.push(new Ciudad('13', 'AGUADAS'));
        c.push(new Ciudad('42', 'ANSERMA'));
        c.push(new Ciudad('50', 'ARANZAZU'));
        c.push(new Ciudad('88', 'BELALCAZAR'));
        c.push(new Ciudad('174', 'CHINCHINA'));
        c.push(new Ciudad('272', 'FILADELFIA'));
        c.push(new Ciudad('380', 'LA DORADA'));
        c.push(new Ciudad('388', 'LA MERCED'));
        c.push(new Ciudad('433', 'MANZANARES'));
        c.push(new Ciudad('442', 'MARMATO'));
        c.push(new Ciudad('444', 'MARQUETALIA'));
        c.push(new Ciudad('446', 'MARULANDA'));
        c.push(new Ciudad('486', 'NEIRA'));
        c.push(new Ciudad('495', 'Norcasia'));
        c.push(new Ciudad('513', 'PACORA'));
        c.push(new Ciudad('524', 'PALESTINA'));
        c.push(new Ciudad('541', 'PENSILVANIA'));
        c.push(new Ciudad('614', 'RIOSUCIO'));
        c.push(new Ciudad('616', 'RISARALDA'));
        c.push(new Ciudad('653', 'SALAMINA'));
        c.push(new Ciudad('662', 'SAMANA'));
        c.push(new Ciudad('665', 'SAN JOSE'));
        c.push(new Ciudad('777', 'SUPIA'));
        c.push(new Ciudad('867', 'VICTORIA'));
        c.push(new Ciudad('873', 'VILLAMARIA'));
        c.push(new Ciudad('877', 'VITERBO'));
        break;
      case '18':
        c.push(new Ciudad('1', 'FLORENCIA'));
        c.push(new Ciudad('29', 'ALBANIA'));
        c.push(new Ciudad('94', 'BELEN DE LOS ANDAQUIES'));
        c.push(new Ciudad('150', 'CARTAGENA DEL CHAIRA'));
        c.push(new Ciudad('205', 'CURRILLO'));
        c.push(new Ciudad('247', 'EL DONCELLO'));
        c.push(new Ciudad('256', 'EL PAUJIL'));
        c.push(new Ciudad('410', 'LA MONTAÑITA'));
        c.push(new Ciudad('460', 'MILAN'));
        c.push(new Ciudad('479', 'MORELIA'));
        c.push(new Ciudad('592', 'PUERTO RICO'));
        c.push(new Ciudad('610', 'SAN JOSE DE LA FRAGUA'));
        c.push(new Ciudad('753', 'SAN VICENTE DEL CAGUAN'));
        c.push(new Ciudad('756', 'SOLANO'));
        c.push(new Ciudad('785', 'SOLITA'));
        c.push(new Ciudad('860', 'VALPARAISO'));
        break;
      case '19':
        c.push(new Ciudad('1', 'POPAYAN'));
        c.push(new Ciudad('22', 'ALMAGUER'));
        c.push(new Ciudad('50', 'ARGELIA'));
        c.push(new Ciudad('75', 'BALBOA'));
        c.push(new Ciudad('100', 'BOLIVAR'));
        c.push(new Ciudad('110', 'BUENOS AIRES'));
        c.push(new Ciudad('130', 'CAJIBIO'));
        c.push(new Ciudad('137', 'CALDONO'));
        c.push(new Ciudad('142', 'CALOTO'));
        c.push(new Ciudad('212', 'CORINTO'));
        c.push(new Ciudad('256', 'EL TAMBO'));
        c.push(new Ciudad('290', 'FLORENCIA'));
        c.push(new Ciudad('300', 'Guachené'));
        c.push(new Ciudad('318', 'GUAPI'));
        c.push(new Ciudad('355', 'INZA'));
        c.push(new Ciudad('364', 'JAMBALO'));
        c.push(new Ciudad('392', 'LA SIERRA'));
        c.push(new Ciudad('397', 'LA VEGA'));
        c.push(new Ciudad('418', 'LOPEZ'));
        c.push(new Ciudad('450', 'MERCADERES'));
        c.push(new Ciudad('455', 'MIRANDA'));
        c.push(new Ciudad('473', 'MORALES'));
        c.push(new Ciudad('513', 'PADILLA'));
        c.push(new Ciudad('517', 'PAEZ'));
        c.push(new Ciudad('532', 'PATIA'));
        c.push(new Ciudad('533', 'PIAMONTE'));
        c.push(new Ciudad('548', 'PIENDAMO'));
        c.push(new Ciudad('573', 'PUERTO TEJADA'));
        c.push(new Ciudad('585', 'PURACE'));
        c.push(new Ciudad('622', 'ROSAS'));
        c.push(new Ciudad('693', 'SAN SEBASTIAN'));
        c.push(new Ciudad('698', 'SANTANDER DE QUILICHAO'));
        c.push(new Ciudad('701', 'SANTA ROSA'));
        c.push(new Ciudad('743', 'SILVIA'));
        c.push(new Ciudad('760', 'SOTARA'));
        c.push(new Ciudad('780', 'SUAREZ'));
        c.push(new Ciudad('785', 'Sucre'));
        c.push(new Ciudad('807', 'TIMBIO'));
        c.push(new Ciudad('809', 'TIMBIQUI'));
        c.push(new Ciudad('821', 'TORIBIO'));
        c.push(new Ciudad('824', 'TOTORO'));
        c.push(new Ciudad('845', 'Villa Rica'));
        break;
      case '20':
        c.push(new Ciudad('1', 'VALLEDUPAR'));
        c.push(new Ciudad('11', 'AGUACHICA'));
        c.push(new Ciudad('13', 'AGUSTIN CODAZZI'));
        c.push(new Ciudad('32', 'ASTREA'));
        c.push(new Ciudad('45', 'Becerril'));
        c.push(new Ciudad('60', 'BOSCONIA'));
        c.push(new Ciudad('175', 'CHIMICHAGUA'));
        c.push(new Ciudad('178', 'CHIRIGUANA'));
        c.push(new Ciudad('228', 'CURUMANI'));
        c.push(new Ciudad('238', 'EL COPEY'));
        c.push(new Ciudad('250', 'EL PASO'));
        c.push(new Ciudad('295', 'GAMARRA'));
        c.push(new Ciudad('310', 'GONZALEZ'));
        c.push(new Ciudad('383', 'LA GLORIA'));
        c.push(new Ciudad('400', 'LA JAGUA DE IBIRICO'));
        c.push(new Ciudad('443', 'MANAURE'));
        c.push(new Ciudad('517', 'PAILITAS'));
        c.push(new Ciudad('550', 'PELAYA'));
        c.push(new Ciudad('570', 'Pueblo Bello'));
        c.push(new Ciudad('614', 'RIO DE ORO'));
        c.push(new Ciudad('621', 'LA PAZ'));
        c.push(new Ciudad('710', 'SAN ALBERTO'));
        c.push(new Ciudad('750', 'SAN DIEGO'));
        c.push(new Ciudad('770', 'SAN MARTIN'));
        c.push(new Ciudad('787', 'TAMALAMEQUE'));
        break;
      case '23':
        c.push(new Ciudad('1', 'MONTERIA'));
        c.push(new Ciudad('68', 'AYAPEL'));
        c.push(new Ciudad('79', 'BUENAVISTA'));
        c.push(new Ciudad('90', 'CANALETE'));
        c.push(new Ciudad('162', 'CERETE'));
        c.push(new Ciudad('168', 'CHIMA'));
        c.push(new Ciudad('182', 'CHINU'));
        c.push(new Ciudad('189', 'CIENAGA DE ORO'));
        c.push(new Ciudad('300', 'Cotorra'));
        c.push(new Ciudad('350', 'La Apartada'));
        c.push(new Ciudad('417', 'LORICA'));
        c.push(new Ciudad('419', 'LOS CORDOBAS'));
        c.push(new Ciudad('464', 'MOMIL'));
        c.push(new Ciudad('466', 'MONTELIBANO'));
        c.push(new Ciudad('500', 'MOÑITOS'));
        c.push(new Ciudad('555', 'PLANETA RICA'));
        c.push(new Ciudad('570', 'PUEBLO NUEVO'));
        c.push(new Ciudad('574', 'PUERTO ESCONDIDO'));
        c.push(new Ciudad('580', 'PUERTO LIBERTADOR'));
        c.push(new Ciudad('586', 'PURISIMA'));
        c.push(new Ciudad('660', 'SAHAGUN'));
        c.push(new Ciudad('670', 'SAN ANDRES DE SOTAVENTO'));
        c.push(new Ciudad('672', 'SAN ANTERO'));
        c.push(new Ciudad('675', 'SAN BERNARDO DEL VIENTO'));
        c.push(new Ciudad('678', 'SAN CARLOS'));
        c.push(new Ciudad('682', 'San José De Uré'));
        c.push(new Ciudad('686', 'SAN PELAYO'));
        c.push(new Ciudad('807', 'TIERRALTA'));
        c.push(new Ciudad('815', 'Tuchín'));
        c.push(new Ciudad('855', 'Valencia'));
        break;
      case '2':
        c.push(new Ciudad('1', 'AGUA DE DIOS -BOGOTA-'));
        c.push(new Ciudad('19', 'ALBAN'));
        c.push(new Ciudad('35', 'ANAPOIMA'));
        c.push(new Ciudad('40', 'ANOLAIMA'));
        c.push(new Ciudad('53', 'ARBELAEZ'));
        c.push(new Ciudad('86', 'BELTRAN'));
        c.push(new Ciudad('95', 'BITUIMA'));
        c.push(new Ciudad('99', 'BOJACA'));
        c.push(new Ciudad('120', 'CABRERA'));
        c.push(new Ciudad('123', 'CACHIPAY'));
        c.push(new Ciudad('126', 'CAJICA'));
        c.push(new Ciudad('148', 'CAPARRAPI'));
        c.push(new Ciudad('151', 'CAQUEZA'));
        c.push(new Ciudad('154', 'CARMEN DE CARUPA'));
        c.push(new Ciudad('168', 'CHAGUANI'));
        c.push(new Ciudad('175', 'CHIA'));
        c.push(new Ciudad('178', 'CHIPAQUE'));
        c.push(new Ciudad('181', 'CHOACHI'));
        c.push(new Ciudad('183', 'CHOCONTA'));
        c.push(new Ciudad('200', 'COGUA'));
        c.push(new Ciudad('214', 'COTA'));
        c.push(new Ciudad('224', 'CUCUNUBA'));
        c.push(new Ciudad('245', 'EL COLEGIO'));
        c.push(new Ciudad('258', 'El Peñón'));
        c.push(new Ciudad('260', 'El Rosal'));
        c.push(new Ciudad('269', 'FACATATIVA'));
        c.push(new Ciudad('279', 'FOMEQUE'));
        c.push(new Ciudad('281', 'FOSCA'));
        c.push(new Ciudad('286', 'FUNZA'));
        c.push(new Ciudad('288', 'FUQUENE'));
        c.push(new Ciudad('290', 'FUSAGASUGA'));
        c.push(new Ciudad('293', 'GACHALA'));
        c.push(new Ciudad('295', 'GACHANCIPA'));
        c.push(new Ciudad('297', 'GACHETA'));
        c.push(new Ciudad('299', 'GAMA'));
        c.push(new Ciudad('307', 'GIRARDOT'));
        c.push(new Ciudad('312', 'GRANADA'));
        c.push(new Ciudad('317', 'GUACHETA'));
        c.push(new Ciudad('320', 'GUADUAS'));
        c.push(new Ciudad('322', 'GUASCA'));
        c.push(new Ciudad('324', 'GUATAQUI'));
        c.push(new Ciudad('326', 'GUATAVITA'));
        c.push(new Ciudad('328', 'GUAYABAL DE SIQUIMA'));
        c.push(new Ciudad('335', 'GUAYABETAL'));
        c.push(new Ciudad('339', 'GUTIERREZ'));
        c.push(new Ciudad('368', 'JERUSALEM'));
        c.push(new Ciudad('372', 'JUNIN'));
        c.push(new Ciudad('377', 'LA CALERA'));
        c.push(new Ciudad('386', 'LA MESA'));
        c.push(new Ciudad('394', 'LA PALMA'));
        c.push(new Ciudad('398', 'LA PEÑA'));
        c.push(new Ciudad('402', 'LA VEGA'));
        c.push(new Ciudad('407', 'LENGUAZAQUE'));
        c.push(new Ciudad('426', 'MACHETA'));
        c.push(new Ciudad('430', 'MADRID'));
        c.push(new Ciudad('436', 'MANTA'));
        c.push(new Ciudad('438', 'MEDINA'));
        c.push(new Ciudad('473', 'MOSQUERA'));
        c.push(new Ciudad('483', 'NARIÑO'));
        c.push(new Ciudad('486', 'NEMOCON'));
        c.push(new Ciudad('488', 'NILO'));
        c.push(new Ciudad('489', 'NIMAIMA'));
        c.push(new Ciudad('491', 'NOCAIMA'));
        c.push(new Ciudad('506', 'OSPINA PEREZ'));
        c.push(new Ciudad('513', 'PACHO'));
        c.push(new Ciudad('518', 'PAIME'));
        c.push(new Ciudad('524', 'PANDI'));
        c.push(new Ciudad('530', 'PARATEBUENO'));
        c.push(new Ciudad('535', 'PASCA'));
        c.push(new Ciudad('572', 'PUERTO SALGAR'));
        c.push(new Ciudad('580', 'PULI'));
        c.push(new Ciudad('592', 'QUEBRADANEGRA'));
        c.push(new Ciudad('594', 'QUETAME'));
        c.push(new Ciudad('596', 'QUIPILE'));
        c.push(new Ciudad('599', 'RAFAEL REYES'));
        c.push(new Ciudad('612', 'RICAURTE'));
        c.push(new Ciudad('645', 'SAN ANTONIO DE TENA'));
        c.push(new Ciudad('649', 'SAN BERNARDO'));
        c.push(new Ciudad('653', 'SAN CAYETANO'));
        c.push(new Ciudad('658', 'SAN FRANCISCO'));
        c.push(new Ciudad('662', 'SAN JUAN DE RIOSECO'));
        c.push(new Ciudad('718', 'SASAIMA'));
        c.push(new Ciudad('736', 'SESQUILE'));
        c.push(new Ciudad('740', 'SIBATE'));
        c.push(new Ciudad('743', 'SILVANIA'));
        c.push(new Ciudad('745', 'SIMIJACA'));
        c.push(new Ciudad('754', 'SOACHA'));
        c.push(new Ciudad('758', 'SOPO'));
        c.push(new Ciudad('769', 'SUBACHOQUE'));
        c.push(new Ciudad('772', 'SUESCA'));
        c.push(new Ciudad('777', 'SUPATA'));
        c.push(new Ciudad('779', 'SUSA'));
        c.push(new Ciudad('781', 'SUTATAUSA'));
        c.push(new Ciudad('785', 'TABIO'));
        c.push(new Ciudad('793', 'TAUSA'));
        c.push(new Ciudad('797', 'TENA'));
        c.push(new Ciudad('799', 'TENJO'));
        c.push(new Ciudad('805', 'TIBACUY'));
        c.push(new Ciudad('807', 'TIBIRITA'));
        c.push(new Ciudad('815', 'TOCAIMA'));
        c.push(new Ciudad('817', 'TOCANCIPA'));
        c.push(new Ciudad('823', 'TOPAIPI'));
        c.push(new Ciudad('839', 'UBALA'));
        c.push(new Ciudad('841', 'UBAQUE'));
        c.push(new Ciudad('843', 'UBATE'));
        c.push(new Ciudad('845', 'UNE'));
        c.push(new Ciudad('851', 'UTICA'));
        c.push(new Ciudad('862', 'VERGARA'));
        c.push(new Ciudad('867', 'VIANI'));
        c.push(new Ciudad('871', 'VILLAGOMEZ'));
        c.push(new Ciudad('873', 'VILLAPINZON'));
        c.push(new Ciudad('875', 'VILLETA'));
        c.push(new Ciudad('878', 'VIOTA'));
        c.push(new Ciudad('885', 'YACOPI'));
        c.push(new Ciudad('898', 'ZIPACON'));
        c.push(new Ciudad('899', 'ZIPAQUIRA'));
        break;
      case '27':
        c.push(new Ciudad('1', 'QUIBDO'));
        c.push(new Ciudad('6', 'ACANDI'));
        c.push(new Ciudad('25', 'ALTO BAUDO'));
        c.push(new Ciudad('50', 'Atrato'));
        c.push(new Ciudad('73', 'BAGADO'));
        c.push(new Ciudad('75', 'BAHIA SOLANO'));
        c.push(new Ciudad('77', 'BAJO BAUDO'));
        c.push(new Ciudad('86', 'Belén de Bajirá1'));
        c.push(new Ciudad('99', 'BOJAYA'));
        c.push(new Ciudad('135', 'EL CANTON DE SAN PABLO'));
        c.push(new Ciudad('150', 'Carmen del Darien'));
        c.push(new Ciudad('160', 'Cértegui'));
        c.push(new Ciudad('205', 'CONDOTO'));
        c.push(new Ciudad('245', 'EL CARMEN DE ATRATO'));
        c.push(new Ciudad('250', 'LITORAL DEL BAJO SAN JUAN'));
        c.push(new Ciudad('361', 'ITSMINA'));
        c.push(new Ciudad('372', 'JURADO'));
        c.push(new Ciudad('413', 'LLORO'));
        c.push(new Ciudad('425', 'Medio Atrato'));
        c.push(new Ciudad('430', 'Medio Baudó'));
        c.push(new Ciudad('450', 'Medio San Juan'));
        c.push(new Ciudad('491', 'NOVITA'));
        c.push(new Ciudad('495', 'NUQUI'));
        c.push(new Ciudad('580', 'Río Iro'));
        c.push(new Ciudad('600', 'Río Quito2'));
        c.push(new Ciudad('615', 'RIOSUCIO'));
        c.push(new Ciudad('660', 'SAN JOSE DEL PALMAR'));
        c.push(new Ciudad('745', 'SIPI'));
        c.push(new Ciudad('787', 'TADO'));
        c.push(new Ciudad('800', 'UNGUIA'));
        c.push(new Ciudad('810', 'Unión Panamericana'));
        break;
      case '41':
        c.push(new Ciudad('1', 'NEIVA'));
        c.push(new Ciudad('6', 'ACEVEDO'));
        c.push(new Ciudad('13', 'AGRADO'));
        c.push(new Ciudad('16', 'AIPE'));
        c.push(new Ciudad('20', 'ALGECIRAS'));
        c.push(new Ciudad('26', 'ALTAMIRA'));
        c.push(new Ciudad('78', 'BARAYA'));
        c.push(new Ciudad('132', 'CAMPOALEGRE'));
        c.push(new Ciudad('206', 'COLOMBIA'));
        c.push(new Ciudad('244', 'ELIAS'));
        c.push(new Ciudad('298', 'GARZON'));
        c.push(new Ciudad('306', 'GIGANTE'));
        c.push(new Ciudad('319', 'GUADALUPE'));
        c.push(new Ciudad('349', 'HOBO'));
        c.push(new Ciudad('357', 'IQUIRA'));
        c.push(new Ciudad('359', 'ISNOS'));
        c.push(new Ciudad('378', 'LA ARGENTINA'));
        c.push(new Ciudad('396', 'LA PLATA'));
        c.push(new Ciudad('483', 'NATAGA'));
        c.push(new Ciudad('503', 'OPORAPA'));
        c.push(new Ciudad('518', 'PAICOL'));
        c.push(new Ciudad('524', 'PALERMO'));
        c.push(new Ciudad('530', 'PALESTINA'));
        c.push(new Ciudad('548', 'PITAL'));
        c.push(new Ciudad('551', 'PITALITO'));
        c.push(new Ciudad('615', 'RIVERA'));
        c.push(new Ciudad('660', 'SALADOBLANCO'));
        c.push(new Ciudad('668', 'SAN AGUSTIN'));
        c.push(new Ciudad('676', 'SANTA MARIA'));
        c.push(new Ciudad('770', 'SUAZA'));
        c.push(new Ciudad('791', 'TARQUI'));
        c.push(new Ciudad('797', 'TESALIA'));
        c.push(new Ciudad('799', 'TELLO'));
        c.push(new Ciudad('801', 'TERUEL'));
        c.push(new Ciudad('807', 'TIMANA'));
        c.push(new Ciudad('872', 'VILLAVIEJA'));
        c.push(new Ciudad('885', 'YAGUARA'));

        break;

      case '44':
        c.push(new Ciudad('1', 'RIOHACHA'));
        c.push(new Ciudad('35', 'Albania'));
        c.push(new Ciudad('78', 'BARRANCAS'));
        c.push(new Ciudad('90', 'DIBULLA'));
        c.push(new Ciudad('98', 'DISTRACCION'));
        c.push(new Ciudad('110', 'EL MOLINO'));
        c.push(new Ciudad('279', 'FONSECA'));
        c.push(new Ciudad('378', 'HATONUEVO'));
        c.push(new Ciudad('420', 'La Jagua del Pilar'));
        c.push(new Ciudad('430', 'MAICAO'));
        c.push(new Ciudad('560', 'MANAURE'));
        c.push(new Ciudad('650', 'SAN JUAN DEL CESAR'));
        c.push(new Ciudad('847', 'URIBIA'));
        c.push(new Ciudad('855', 'URUMITA'));
        c.push(new Ciudad('874', 'VILLANUEVA'));
        break;
      case '47':
        c.push(new Ciudad('1', 'SANTA MARTA'));
        c.push(new Ciudad('30', 'Algarrobo'));
        c.push(new Ciudad('53', 'Aracataca'));
        c.push(new Ciudad('58', 'ARIGUANI'));
        c.push(new Ciudad('161', 'CERRO SAN ANTONIO'));
        c.push(new Ciudad('170', 'CHIVOLO'));
        c.push(new Ciudad('189', 'CIENAGA'));
        c.push(new Ciudad('205', 'Concordia'));
        c.push(new Ciudad('245', 'EL BANCO'));
        c.push(new Ciudad('258', 'EL PIÑON'));
        c.push(new Ciudad('268', 'EL RETEN'));
        c.push(new Ciudad('288', 'FUNDACION'));
        c.push(new Ciudad('318', 'GUAMAL'));
        c.push(new Ciudad('460', 'Nueva Granada'));
        c.push(new Ciudad('541', 'PEDRAZA'));
        c.push(new Ciudad('545', 'PIJIÑO DEL CARMEN'));
        c.push(new Ciudad('551', 'PIVIJAY'));
        c.push(new Ciudad('555', 'PLATO'));
        c.push(new Ciudad('570', 'PUEBLO VIEJO'));
        c.push(new Ciudad('605', 'REMOLINO'));
        c.push(new Ciudad('660', 'Sabanas de San Angel'));
        c.push(new Ciudad('675', 'SALAMINA'));
        c.push(new Ciudad('692', 'SAN SEBASTIAN BUENAVISTA'));
        c.push(new Ciudad('703', 'SAN ZENON'));
        c.push(new Ciudad('707', 'SANTA ANA'));
        c.push(new Ciudad('720', 'Santa Bárbara de Pinto'));
        c.push(new Ciudad('745', 'SITIONUEVO'));
        c.push(new Ciudad('798', 'TENERIFE'));
        c.push(new Ciudad('960', 'Zapayán'));
        c.push(new Ciudad('980', 'Zona Bananera'));

        break;
      case '50':
        c.push(new Ciudad('1', 'VILLAVICENCIO'));
        c.push(new Ciudad('6', 'ACACIAS'));
        c.push(new Ciudad('110', 'BARRANCA DE UPIA'));
        c.push(new Ciudad('124', 'CABUYARO'));
        c.push(new Ciudad('150', 'Castilla la Nueva'));
        c.push(new Ciudad('223', 'Cubarral'));
        c.push(new Ciudad('226', 'CUMARAL'));
        c.push(new Ciudad('245', 'EL CALVARIO'));
        c.push(new Ciudad('251', 'EL CASTILLO'));
        c.push(new Ciudad('270', 'EL DORADO'));
        c.push(new Ciudad('287', 'FUENTE DE ORO'));
        c.push(new Ciudad('313', 'GRANADA'));
        c.push(new Ciudad('318', 'GUAMAL'));
        c.push(new Ciudad('325', 'MAPIRIPAN'));
        c.push(new Ciudad('330', 'MESETAS'));
        c.push(new Ciudad('350', 'La Macarena'));
        c.push(new Ciudad('370', 'LA URIBE'));
        c.push(new Ciudad('400', 'LEJANIAS'));
        c.push(new Ciudad('450', 'Puerto Concordia'));
        c.push(new Ciudad('568', 'PUERTO GAITAN'));
        c.push(new Ciudad('573', 'PUERTO LOPEZ'));
        c.push(new Ciudad('577', 'PUERTO LLERAS'));
        c.push(new Ciudad('590', 'PUERTO RICO'));
        c.push(new Ciudad('606', 'RESTREPO'));
        c.push(new Ciudad('680', 'SAN CARLOS GUAROA'));
        c.push(new Ciudad('683', 'SAN JUAN DE ARAMA'));
        c.push(new Ciudad('686', 'SAN JUANITO'));
        c.push(new Ciudad('689', 'SAN MARTIN'));
        c.push(new Ciudad('711', 'VISTA HERMOSA'));
        break;
      case '52':
        c.push(new Ciudad('1', 'PASTO'));
        c.push(new Ciudad('19', 'ALBAN'));
        c.push(new Ciudad('22', 'ALDANA'));
        c.push(new Ciudad('36', 'ANCUYA'));
        c.push(new Ciudad('51', 'ARBOLEDA'));
        c.push(new Ciudad('79', 'BARBACOAS'));
        c.push(new Ciudad('83', 'BELEN'));
        c.push(new Ciudad('110', 'BUESACO'));
        c.push(new Ciudad('203', 'COLON'));
        c.push(new Ciudad('207', 'CONSACA'));
        c.push(new Ciudad('210', 'CONTADERO'));
        c.push(new Ciudad('215', 'CORDOBA'));
        c.push(new Ciudad('224', 'CUASPUD'));
        c.push(new Ciudad('227', 'CUMBAL'));
        c.push(new Ciudad('233', 'CUMBITARA'));
        c.push(new Ciudad('240', 'CHACHAGUI'));
        c.push(new Ciudad('250', 'EL CHARCO'));
        c.push(new Ciudad('254', 'El Peñol'));
        c.push(new Ciudad('256', 'EL ROSARIO'));
        c.push(new Ciudad('258', 'EL TABLON'));
        c.push(new Ciudad('260', 'EL TAMBO'));
        c.push(new Ciudad('287', 'FUNES'));
        c.push(new Ciudad('317', 'GUACHUCAL'));
        c.push(new Ciudad('320', 'GUAITARILLA'));
        c.push(new Ciudad('323', 'GUALMATAN'));
        c.push(new Ciudad('352', 'Iles'));
        c.push(new Ciudad('354', 'IMUES'));
        c.push(new Ciudad('356', 'IPIALES'));
        c.push(new Ciudad('378', 'LA CRUZ'));
        c.push(new Ciudad('381', 'LA FLORIDA'));
        c.push(new Ciudad('385', 'LA LLANADA'));
        c.push(new Ciudad('390', 'LA TOLA'));
        c.push(new Ciudad('399', 'LA UNION'));
        c.push(new Ciudad('405', 'LEIVA'));
        c.push(new Ciudad('411', 'LINARES'));
        c.push(new Ciudad('418', 'LOS ANDES'));
        c.push(new Ciudad('427', 'MAGUI'));
        c.push(new Ciudad('435', 'MALLAMA'));
        c.push(new Ciudad('473', 'MOSQUERA'));
        c.push(new Ciudad('480', 'Nariño'));
        c.push(new Ciudad('490', 'OLAYA HERRERA'));
        c.push(new Ciudad('506', 'OSPINA'));
        c.push(new Ciudad('520', 'FRANCISCO PIZARRO'));
        c.push(new Ciudad('540', 'POLICARPA'));
        c.push(new Ciudad('560', 'POTOSI'));
        c.push(new Ciudad('565', 'PROVIDENCIA'));
        c.push(new Ciudad('573', 'PUERRES'));
        c.push(new Ciudad('585', 'PUPIALES'));
        c.push(new Ciudad('612', 'RICAURTE'));
        c.push(new Ciudad('621', 'ROBERTO PAYAN'));
        c.push(new Ciudad('678', 'SAMANIEGO'));
        c.push(new Ciudad('683', 'SANDONA'));
        c.push(new Ciudad('685', 'SAN BERNARDO'));
        c.push(new Ciudad('687', 'SAN LORENZO'));
        c.push(new Ciudad('693', 'SAN PABLO'));
        c.push(new Ciudad('694', 'SAN PEDRO DE CARTAGO'));
        c.push(new Ciudad('696', 'SANTA BARBARA'));
        c.push(new Ciudad('699', 'SANTACRUZ'));
        c.push(new Ciudad('720', 'SAPUYES'));
        c.push(new Ciudad('786', 'TAMINANGO'));
        c.push(new Ciudad('788', 'TANGUA'));
        c.push(new Ciudad('835', 'TUMACO'));
        c.push(new Ciudad('838', 'TUQUERRES'));
        c.push(new Ciudad('885', 'YUCUANQUER'));

        break;
      case '54':
        c.push(new Ciudad('1', 'CUCUTA'));
        c.push(new Ciudad('3', 'ABREGO'));
        c.push(new Ciudad('51', 'ARBOLEDAS'));
        c.push(new Ciudad('99', 'BOCHALEMA'));
        c.push(new Ciudad('109', 'BUCARASICA'));
        c.push(new Ciudad('125', 'CACOTA'));
        c.push(new Ciudad('128', 'CACHIRA'));
        c.push(new Ciudad('172', 'CHINACOTA'));
        c.push(new Ciudad('174', 'CHITAGA'));
        c.push(new Ciudad('206', 'CONVENCION'));
        c.push(new Ciudad('223', 'CUCUTILLA'));
        c.push(new Ciudad('239', 'DURANIA'));
        c.push(new Ciudad('245', 'EL CARMEN'));
        c.push(new Ciudad('250', 'EL TARRA'));
        c.push(new Ciudad('261', 'EL ZULIA'));
        c.push(new Ciudad('313', 'GRAMALOTE'));
        c.push(new Ciudad('344', 'HACARI'));
        c.push(new Ciudad('347', 'HERRAN'));
        c.push(new Ciudad('377', 'LABATECA'));
        c.push(new Ciudad('385', 'LA ESPERANZA'));
        c.push(new Ciudad('398', 'LA PLAYA'));
        c.push(new Ciudad('405', 'LOS PATIOS'));
        c.push(new Ciudad('418', 'LOURDES'));
        c.push(new Ciudad('480', 'MUTISCUA'));
        c.push(new Ciudad('498', 'OCAÑA'));
        c.push(new Ciudad('518', 'PAMPLONA'));
        c.push(new Ciudad('520', 'PAMPLONITA'));
        c.push(new Ciudad('553', 'PUERTO SANTANDER'));
        c.push(new Ciudad('599', 'RAGONVALIA'));
        c.push(new Ciudad('660', 'SALAZAR'));
        c.push(new Ciudad('670', 'SAN CALIXTO'));
        c.push(new Ciudad('673', 'SAN CAYETANO'));
        c.push(new Ciudad('680', 'SANTIAGO'));
        c.push(new Ciudad('720', 'SARDINATA'));
        c.push(new Ciudad('743', 'SILOS'));
        c.push(new Ciudad('800', 'TEORAMA'));
        c.push(new Ciudad('810', 'TIBU'));
        c.push(new Ciudad('820', 'TOLEDO'));
        c.push(new Ciudad('871', 'VILLA CARO'));
        c.push(new Ciudad('874', 'VILLA DEL ROSARIO'));
        break;
      case '63':
        c.push(new Ciudad('1', 'ARMENIA'));
        c.push(new Ciudad('111', 'BUENAVISTA'));
        c.push(new Ciudad('130', 'CALARCA'));
        c.push(new Ciudad('190', 'CIRCASIA'));
        c.push(new Ciudad('212', 'CORDOBA'));
        c.push(new Ciudad('272', 'FILANDIA'));
        c.push(new Ciudad('302', 'GENOVA'));
        c.push(new Ciudad('401', 'LA TEBAIDA'));
        c.push(new Ciudad('470', 'MONTENEGRO'));
        c.push(new Ciudad('548', 'PIJAO'));
        c.push(new Ciudad('594', 'QUIMBAYA'));
        c.push(new Ciudad('690', 'SALENTO'));
        break;
      case '66':
        c.push(new Ciudad('1', 'PEREIRA'));
        c.push(new Ciudad('45', 'APIA'));
        c.push(new Ciudad('75', 'BALBOA'));
        c.push(new Ciudad('88', 'BELEN DE UMBRIA'));
        c.push(new Ciudad('170', 'DOSQUEBRADAS'));
        c.push(new Ciudad('318', 'GUATICA'));
        c.push(new Ciudad('383', 'LA CELIA'));
        c.push(new Ciudad('400', 'LA VIRGINIA'));
        c.push(new Ciudad('440', 'MARSELLA'));
        c.push(new Ciudad('456', 'MISTRATO'));
        c.push(new Ciudad('572', 'PUEBLO RICO'));
        c.push(new Ciudad('594', 'QUINCHIA'));
        c.push(new Ciudad('682', 'SANTA ROSA DE CABAL'));
        c.push(new Ciudad('687', 'SANTUARIO'));
        break;
      case '68':
        c.push(new Ciudad('1', 'BUCARAMANGA'));
        c.push(new Ciudad('13', 'AGUADA'));
        c.push(new Ciudad('20', 'ALBANIA'));
        c.push(new Ciudad('51', 'ARATOCA'));
        c.push(new Ciudad('77', 'BARBOSA'));
        c.push(new Ciudad('79', 'BARICHARA'));
        c.push(new Ciudad('81', 'BARRANCABERMEJA'));
        c.push(new Ciudad('92', 'BETULIA'));
        c.push(new Ciudad('101', 'BOLIVAR'));
        c.push(new Ciudad('121', 'CABRERA'));
        c.push(new Ciudad('132', 'CALIFORNIA'));
        c.push(new Ciudad('147', 'CAPITANEJO'));
        c.push(new Ciudad('152', 'CARCASI'));
        c.push(new Ciudad('160', 'CEPITA'));
        c.push(new Ciudad('162', 'CERRITO'));
        c.push(new Ciudad('167', 'CHARALA'));
        c.push(new Ciudad('169', 'CHARTA'));
        c.push(new Ciudad('176', 'CHIMA'));
        c.push(new Ciudad('179', 'CHIPATA'));
        c.push(new Ciudad('190', 'CIMITARRA'));
        c.push(new Ciudad('207', 'CONCEPCION'));
        c.push(new Ciudad('209', 'CONFINES'));
        c.push(new Ciudad('211', 'CONTRATACION'));
        c.push(new Ciudad('217', 'COROMORO'));
        c.push(new Ciudad('229', 'CURITI'));
        c.push(new Ciudad('235', 'EL CARMEN DE CHUCURI'));
        c.push(new Ciudad('245', 'EL GUACAMAYO'));
        c.push(new Ciudad('250', 'EL PEÑON'));
        c.push(new Ciudad('255', 'EL PLAYON'));
        c.push(new Ciudad('264', 'ENCINO'));
        c.push(new Ciudad('266', 'ENCISO'));
        c.push(new Ciudad('271', 'EL FLORIAN'));
        c.push(new Ciudad('276', 'FLORIDABLANCA'));
        c.push(new Ciudad('296', 'GALAN'));
        c.push(new Ciudad('298', 'GAMBITA'));
        c.push(new Ciudad('307', 'GIRON'));
        c.push(new Ciudad('318', 'GUACA'));
        c.push(new Ciudad('320', 'GUADALUPE'));
        c.push(new Ciudad('322', 'GUAPOTA'));
        c.push(new Ciudad('324', 'GUAVATA'));
        c.push(new Ciudad('327', 'GUEPSA'));
        c.push(new Ciudad('344', 'HATO'));
        c.push(new Ciudad('368', 'Jesús María'));
        c.push(new Ciudad('370', 'JORDAN'));
        c.push(new Ciudad('377', 'LA BELLEZA'));
        c.push(new Ciudad('385', 'LANDAZURI'));
        c.push(new Ciudad('397', 'LA PAZ'));
        c.push(new Ciudad('406', 'LEBRIJA'));
        c.push(new Ciudad('418', 'LOS SANTOS'));
        c.push(new Ciudad('425', 'MACARAVITA'));
        c.push(new Ciudad('432', 'MALAGA'));
        c.push(new Ciudad('444', 'MATANZA'));
        c.push(new Ciudad('464', 'MOGOTES'));
        c.push(new Ciudad('468', 'Molagavita'));
        c.push(new Ciudad('498', 'OCAMONTE'));
        c.push(new Ciudad('500', 'OIBA'));
        c.push(new Ciudad('502', 'ONZAGA'));
        c.push(new Ciudad('522', 'PALMAR'));
        c.push(new Ciudad('524', 'PALMAS DEL SOCORRO'));
        c.push(new Ciudad('533', 'PARAMO'));
        c.push(new Ciudad('547', 'PIEDECUESTA'));
        c.push(new Ciudad('549', 'PINCHOTE'));
        c.push(new Ciudad('572', 'Puente Nacional'));
        c.push(new Ciudad('573', 'Puerto Parra'));
        c.push(new Ciudad('575', 'Puerto Wilches'));
        c.push(new Ciudad('615', 'Rionegro'));
        c.push(new Ciudad('655', 'Sabana de Torres'));
        c.push(new Ciudad('669', 'San Andrés'));
        c.push(new Ciudad('673', 'San Benito'));
        c.push(new Ciudad('679', 'San Gil'));
        c.push(new Ciudad('682', 'San Joaquín'));
        c.push(new Ciudad('684', 'San José de Miranda'));
        c.push(new Ciudad('686', 'San Miguel'));
        c.push(new Ciudad('689', 'San Vicente de Chucurí'));
        c.push(new Ciudad('705', 'Santa Bárbara'));
        c.push(new Ciudad('720', 'Santa Helena del Opón'));
        c.push(new Ciudad('745', 'Simacota'));
        c.push(new Ciudad('755', 'Socorro'));
        c.push(new Ciudad('770', 'Suaita'));
        c.push(new Ciudad('773', 'Sucre'));
        c.push(new Ciudad('780', 'Suratá'));
        c.push(new Ciudad('820', 'Tona'));
        c.push(new Ciudad('855', 'Valle de San José'));
        c.push(new Ciudad('861', 'VELEZ SANTANDER'));
        c.push(new Ciudad('867', 'Vetas'));
        c.push(new Ciudad('872', 'Villanueva'));
        c.push(new Ciudad('895', 'Zapatoca'));
        break;
      case '70':
        c.push(new Ciudad('1', 'SINCELEJO'));
        c.push(new Ciudad('110', 'BUENAVISTA'));
        c.push(new Ciudad('124', 'CAIMITO'));
        c.push(new Ciudad('204', 'COLOSO'));
        c.push(new Ciudad('215', 'COROZAL'));
        c.push(new Ciudad('221', 'Coveñas'));
        c.push(new Ciudad('230', 'CHALAN'));
        c.push(new Ciudad('233', 'El Roble'));
        c.push(new Ciudad('235', 'GALERAS'));
        c.push(new Ciudad('265', 'GUARANDA'));
        c.push(new Ciudad('400', 'LA UNION'));
        c.push(new Ciudad('418', 'LOS PALMITOS'));
        c.push(new Ciudad('429', 'MAJAGUAL'));
        c.push(new Ciudad('473', 'MORROA'));
        c.push(new Ciudad('508', 'OVEJAS'));
        c.push(new Ciudad('523', 'PALMITO'));
        c.push(new Ciudad('670', 'Sampués'));
        c.push(new Ciudad('678', 'SAN BENITO ABAD'));
        c.push(new Ciudad('702', 'SAN JUAN BETULIA'));
        c.push(new Ciudad('708', 'SAN MARCOS'));
        c.push(new Ciudad('713', 'SAN ONOFRE'));
        c.push(new Ciudad('717', 'SAN PEDRO'));
        c.push(new Ciudad('742', 'SINCE'));
        c.push(new Ciudad('771', 'SUCRE'));
        c.push(new Ciudad('820', 'TOLU'));
        c.push(new Ciudad('823', 'TOLUVIEJO'));
        break;
    case '73':
      c.push(new Ciudad('1', 'IBAGUE'));
      c.push(new Ciudad('24', 'ALPUJARRA'));
      c.push(new Ciudad('26', 'ALVARADO'));
      c.push(new Ciudad('30', 'AMBALEMA'));
      c.push(new Ciudad('43', 'ANZOATEGUI'));
      c.push(new Ciudad('55', 'ARMERO'));
      c.push(new Ciudad('67', 'ATACO'));
      c.push(new Ciudad('124', 'CAJAMARCA'));
      c.push(new Ciudad('148', 'CARMEN APICALA'));
      c.push(new Ciudad('152', 'CASABIANCA'));
      c.push(new Ciudad('168', 'CHAPARRAL'));
      c.push(new Ciudad('200', 'COELLO'));
      c.push(new Ciudad('217', 'COYAIMA'));
      c.push(new Ciudad('226', 'CUNDAY'));
      c.push(new Ciudad('236', 'DOLORES'));
      c.push(new Ciudad('268', 'ESPINAL'));
      c.push(new Ciudad('270', 'FALAN'));
      c.push(new Ciudad('275', 'FLANDES'));
      c.push(new Ciudad('283', 'FRESNO'));
      c.push(new Ciudad('319', 'GUAMO'));
      c.push(new Ciudad('347', 'HERVEO'));
      c.push(new Ciudad('349', 'HONDA'));
      c.push(new Ciudad('352', 'ICONONZO'));
      c.push(new Ciudad('408', 'LERIDA'));
      c.push(new Ciudad('411', 'LIBANO'));
      c.push(new Ciudad('443', 'MARIQUITA'));
      c.push(new Ciudad('449', 'MELGAR'));
      c.push(new Ciudad('461', 'MURILLO'));
      c.push(new Ciudad('483', 'NATAGAIMA'));
      c.push(new Ciudad('504', 'ORTEGA'));
      c.push(new Ciudad('520', 'PALOCABILDO'));
      c.push(new Ciudad('547', 'PIEDRAS'));
      c.push(new Ciudad('555', 'PLANADAS'));
      c.push(new Ciudad('563', 'PRADO'));
      c.push(new Ciudad('585', 'PURIFICACION'));
      c.push(new Ciudad('616', 'RIOBLANCO'));
      c.push(new Ciudad('622', 'RONCESVALLES'));
      c.push(new Ciudad('624', 'ROVIRA'));
      c.push(new Ciudad('671', 'SALDAÑA'));
      c.push(new Ciudad('675', 'SAN ANTONIO'));
      c.push(new Ciudad('678', 'SAN LUIS'));
      c.push(new Ciudad('686', 'SANTA ISABEL'));
      c.push(new Ciudad('770', 'SUAREZ'));
      c.push(new Ciudad('854', 'VALLE DE SAN JUAN'));
      c.push(new Ciudad('861', 'VENADILLO'));
      c.push(new Ciudad('870', 'VILLAHERMOSA'));
      c.push(new Ciudad('873', 'Villarrica'));
      break;
    case '76':
      c.push(new Ciudad('1', 'CALI'));
      c.push(new Ciudad('20', 'ALCALA'));
      c.push(new Ciudad('36', 'ANDALUCIA'));
      c.push(new Ciudad('41', 'ANSERMANUEVO'));
      c.push(new Ciudad('54', 'ARGELIA'));
      c.push(new Ciudad('100', 'BOLIVAR'));
      c.push(new Ciudad('109', 'BUENAVENTURA'));
      c.push(new Ciudad('111', 'BUGA'));
      c.push(new Ciudad('113', 'BUGALAGRANDE'));
      c.push(new Ciudad('122', 'CAICEDONIA'));
      c.push(new Ciudad('126', 'CALIMA'));
      c.push(new Ciudad('130', 'CANDELARIA'));
      c.push(new Ciudad('147', 'CARTAGO'));
      c.push(new Ciudad('233', 'DAGUA'));
      c.push(new Ciudad('243', 'EL AGUILA'));
      c.push(new Ciudad('246', 'EL CAIRO'));
      c.push(new Ciudad('248', 'EL CERRITO'));
      c.push(new Ciudad('250', 'EL DOVIO'));
      c.push(new Ciudad('275', 'FLORIDA'));
      c.push(new Ciudad('306', 'GINEBRA'));
      c.push(new Ciudad('318', 'GUACARI'));
      c.push(new Ciudad('364', 'JAMUNDI'));
      c.push(new Ciudad('377', 'LA CUMBRE'));
      c.push(new Ciudad('400', 'LA UNION'));
      c.push(new Ciudad('403', 'LA VICTORIA'));
      c.push(new Ciudad('497', 'OBANDO'));
      c.push(new Ciudad('520', 'PALMIRA'));
      c.push(new Ciudad('563', 'PRADERA'));
      c.push(new Ciudad('606', 'RESTREPO'));
      c.push(new Ciudad('616', 'RIOFRIO'));
      c.push(new Ciudad('622', 'ROLDANILLO'));
      c.push(new Ciudad('670', 'SAN PEDRO'));
      c.push(new Ciudad('736', 'SEVILLA'));
      c.push(new Ciudad('823', 'TORO'));
      c.push(new Ciudad('828', 'TRUJILLO'));
      c.push(new Ciudad('834', 'TULUA'));
      c.push(new Ciudad('845', 'ULLOA'));
      c.push(new Ciudad('863', 'VERSALLES'));
      c.push(new Ciudad('869', 'VIJES'));
      c.push(new Ciudad('890', 'YOTOCO'));
      c.push(new Ciudad('892', 'YUMBO'));
      c.push(new Ciudad('895', 'ZARZAL'));
      break;
    case '81':
      c.push(new Ciudad('1', 'ARAUCA'));
      c.push(new Ciudad('65', 'ARAUQUITA'));
      c.push(new Ciudad('220', 'CRAVO NORTE'));
      c.push(new Ciudad('300', 'FORTUL'));
      c.push(new Ciudad('591', 'PUERTO RONDON'));
      c.push(new Ciudad('736', 'SARAVENA'));
      c.push(new Ciudad('794', 'TAME'));
      break;
    case '85':
      c.push(new Ciudad('1', 'YOPAL'));
      c.push(new Ciudad('10', 'AGUAZUL'));
      c.push(new Ciudad('15', 'CHAMEZA'));
      c.push(new Ciudad('125', 'HATO COROZAL'));
      c.push(new Ciudad('136', 'LA SALINA'));
      c.push(new Ciudad('139', 'MANI'));
      c.push(new Ciudad('162', 'MONTERREY'));
      c.push(new Ciudad('225', 'NUNCHIA'));
      c.push(new Ciudad('230', 'OROCUE'));
      c.push(new Ciudad('250', 'PAZ DE ARIPORO'));
      c.push(new Ciudad('263', 'PORE'));
      c.push(new Ciudad('279', 'RECETOR'));
      c.push(new Ciudad('300', 'SABANALARGA'));
      c.push(new Ciudad('315', 'SACAMA'));
      c.push(new Ciudad('325', 'SAN LUIS DE PALENQUE'));
      c.push(new Ciudad('400', 'TAMARA'));
      c.push(new Ciudad('410', 'TAURAMENA'));
      c.push(new Ciudad('430', 'TRINIDAD'));
      c.push(new Ciudad('440', 'VILLANUEVA'));
      break;
    case '86':
      c.push(new Ciudad('1', 'MOCOA'));
      c.push(new Ciudad('219', 'COLON'));
      c.push(new Ciudad('320', 'ORITO'));
      c.push(new Ciudad('568', 'PUERTO ASIS'));
      c.push(new Ciudad('569', 'PUERTO CAICEDO'));
      c.push(new Ciudad('571', 'PUERTO GUZMAN'));
      c.push(new Ciudad('573', 'PUERTO LEGUIZAMO'));
      c.push(new Ciudad('749', 'SIBUNDOY'));
      c.push(new Ciudad('755', 'SAN FRANCISCO'));
      c.push(new Ciudad('757', 'LA DORADA'));
      c.push(new Ciudad('760', 'SANTIAGO'));
      c.push(new Ciudad('865', 'VALLE DEL GUAMEZ'));
      c.push(new Ciudad('885', 'VILLAGARZON'));
      break;
    case '88':
      c.push(new Ciudad('1', 'SAN ANDRES'));
      c.push(new Ciudad('564', 'PROVIDENCIA'));
      break;
    case '91':
      c.push(new Ciudad('1', 'LETICIA'));
      c.push(new Ciudad('263', 'EL ENCANTO'));
      c.push(new Ciudad('405', 'LA CHORRERA'));
      c.push(new Ciudad('407', 'LA PEDRERA'));
      c.push(new Ciudad('430', 'La Victoria'));
      c.push(new Ciudad('460', 'MIRITI-PARANA'));
      c.push(new Ciudad('530', 'Puerto Alegría'));
      c.push(new Ciudad('536', 'Puerto Arica'));
      c.push(new Ciudad('540', 'PUERTO NARIÑO'));
      c.push(new Ciudad('669', 'PUERTO SANTANDER'));
      c.push(new Ciudad('798', 'TARAPACA'));
      break;
    case '94':
      c.push(new Ciudad('1', 'INIRIDA'));
      c.push(new Ciudad('343', 'BARRANCO MINA'));
      c.push(new Ciudad('663', 'Mapiripana'));
      c.push(new Ciudad('883', 'SAN FELIPE'));
      c.push(new Ciudad('884', 'PUERTO COLOMBIA'));
      c.push(new Ciudad('885', 'LA GUADALUPE'));
      c.push(new Ciudad('886', 'CACAHUAL'));
      c.push(new Ciudad('887', 'PANA PANA'));
      c.push(new Ciudad('888', 'MORICHAL NUEVO'));
      break;
    case '9':
      c.push(new Ciudad('1', 'SAN JOSE DEL GUAVIARE'));
      c.push(new Ciudad('15', 'CALAMAR'));
      c.push(new Ciudad('25', 'EL RETORNO'));
      c.push(new Ciudad('200', 'MIRAFLORES'));
      break;
    case '97':
      c.push(new Ciudad('1', 'MITU'));
      c.push(new Ciudad('161', 'CARURU'));
      c.push(new Ciudad('511', 'PACOA'));
      c.push(new Ciudad('666', 'TARAIRA'));
      c.push(new Ciudad('777', 'PAPUNAHUA'));
      c.push(new Ciudad('889', 'YAVARETE'));
      break;
    case '99':
      c.push(new Ciudad('1', 'PUERTO CARREÑO'));
      c.push(new Ciudad('524', 'LA PRIMAVERA'));
      c.push(new Ciudad('624', 'SANTA ROSALIA'));
      c.push(new Ciudad('773', 'CUMARIBO'));
      break;
    default:
        c.push(new Ciudad('0', 'Codigo ' + nombredepto + ' no existe'));
    }

    return c;
  }
}
