import { RouteInfo } from './sidebar.metadata';

const ADMIN  = 'ADMINISTRADOR';
const COORD  = 'COORDINADOR';
const INSTR  = 'INSTRUCTOR';

export const ROUTES: RouteInfo[] = [
  {
    path: '/admin/dashboard/main',
    title: 'Home',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN, COORD],
    submenu: [],
  },
  {
    path: '/teacher/permiso-trabajo',
    title: 'Permiso de trabajo',
    moduleName: 'teacher',
    iconType: 'material-icons-two-tone',
    icon: 'engineering',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [INSTR, ADMIN, COORD],
    submenu: [],
  },
  {
    path: '/admin/students/preinscripcionlector',
    title: 'Lector Preinscripción',
    moduleName: 'admin',
    iconType: 'material-icons-two-tone',
    icon: 'qr_code_scanner',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN, COORD],
    submenu: [],
  },
  {
    path: '',
    title: 'Aprendices',
    moduleName: 'students',
    iconType: 'material-icons-two-tone',
    icon: 'people_alt',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN, COORD],
    submenu: [
      {
        path: 'admin/students/wizard',
        title: 'Adicionar aprendiz',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN, COORD],
        submenu: [],
      },
      {
        path: 'admin/empresas/all-empresas',
        title: 'Empresas',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN, COORD],
        submenu: [],
      },
      {
        path: 'admin/empresas/pagospendientes',
        title: 'Pagos pendientes',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN, COORD],
        submenu: [],
      },
      {
        path: 'admin/students/listadoaprendices',
        title: 'Listado aprendices',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN, COORD],
        submenu: [],
      },
      {
        path: 'admin/eps/all-eps',
        title: 'Eps',
        moduleName: 'students',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN, COORD],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Cursos',
    moduleName: 'programs',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN],
    submenu: [
      {
        path: 'admin/programs/all-programs',
        title: 'Programas',
        moduleName: 'programs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN],
        submenu: [],
      },
      {
        path: 'admin/nivels/all-nivels',
        title: 'Niveles',
        moduleName: 'programs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN],
        submenu: [],
      },
      {
        path: 'admin/grupopregunta/all-grupopregunta',
        title: 'Preguntas',
        moduleName: 'programs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN],
        submenu: [],
      },
      {
        path: 'admin/enfasis',
        title: 'Enfasis',
        moduleName: 'programs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [ADMIN],
        submenu: [],
      },
    ],
  },
  {
    path: '/admin/professors/all-professors',
    title: 'Instructores',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'badge',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN],
    submenu: [],
  },
  {
    path: '/admin/dashboard/cambioclave',
    title: 'Cambiar contraseña',
    moduleName: 'logout',
    iconType: 'material-icons-two-tone',
    icon: 'lock',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ADMIN, COORD, INSTR],
    submenu: [],
  },
];
