package com.seguridadlimite.util;

public class UtilidadesPaises {

    public static String getPais(String codigoPais) {
        if (codigoPais == null) {
            return "País no definido";
        }
        switch (codigoPais.toUpperCase()) {
            case "AF": return "Afganistán";
            case "AL": return "Albania";
            case "DZ": return "Argelia";
            case "AS": return "Samoa Americana";
            case "AD": return "Andorra";
            case "AO": return "Angola";
            case "AI": return "Anguila";
            case "AQ": return "Antártida";
            case "AG": return "Antigua y Barbuda";
            case "AR": return "Argentina";
            case "AM": return "Armenia";
            case "AW": return "Aruba";
            case "AU": return "Australia";
            case "AT": return "Austria";
            case "AZ": return "Azerbaiyán";
            case "BS": return "Bahamas";
            case "BH": return "Bahrein";
            case "BD": return "Bangladesh";
            case "BB": return "Barbados";
            case "BY": return "Bielorrusia";
            case "BE": return "Bélgica";
            case "BZ": return "Belice";
            case "BJ": return "Benín";
            case "BM": return "Bermudas";
            case "BT": return "Bután";
            case "BO": return "Bolivia";
            case "BA": return "Bosnia y Herzegovina";
            case "BW": return "Botswana";
            case "BR": return "Brasil";
            case "IO": return "Territorio Británico del Océano Índico";
            case "VG": return "Islas Vírgenes Británicas";
            case "BN": return "Brunei";
            case "BG": return "Bulgaria";
            case "BF": return "Burkina Faso";
            case "BI": return "Burundi";
            case "KH": return "Camboya";
            case "CM": return "Camerún";
            case "CA": return "Canadá";
            case "CV": return "Cabo Verde";
            case "KY": return "Islas Caimán";
            case "CF": return "República Centroafricana";
            case "TD": return "Chad";
            case "CL": return "Chile";
            case "CN": return "China";
            case "CX": return "Isla de Navidad";
            case "CC": return "Islas Cocos";
            case "CO": return "Colombia";
            case "KM": return "Comoras";
            case "CK": return "Islas Cook";
            case "CR": return "Costa Rica";
            case "CI": return "Costa de Marfil";
            case "HR": return "Croacia";
            case "CU": return "Cuba";
            case "CW": return "Curazao";
            case "CY": return "Chipre";
            case "CZ": return "República Checa";
            case "CD": return "República Democrática del Congo";
            case "DK": return "Dinamarca";
            case "DJ": return "Yibuti";
            case "DM": return "Dominica";
            case "DO": return "República Dominicana";
            case "EC": return "Ecuador";
            case "EG": return "Egipto";
            case "SV": return "El Salvador";
            case "GQ": return "Guinea Ecuatorial";
            case "ER": return "Eritrea";
            case "EE": return "Estonia";
            case "SZ": return "Esuatini";
            case "ET": return "Etiopía";
            case "FK": return "Islas Malvinas";
            case "FO": return "Islas Feroe";
            case "FJ": return "Fiyi";
            case "FI": return "Finlandia";
            case "FR": return "Francia";
            case "GF": return "Guayana Francesa";
            case "PF": return "Polinesia Francesa";
            case "GA": return "Gabón";
            case "GM": return "Gambia";
            case "GE": return "Georgia";
            case "DE": return "Alemania";
            case "GH": return "Ghana";
            case "GI": return "Gibraltar";
            case "GR": return "Grecia";
            case "GL": return "Groenlandia";
            case "GD": return "Granada";
            case "GP": return "Guadalupe";
            case "GU": return "Guam";
            case "GT": return "Guatemala";
            case "GG": return "Guernsey";
            case "GN": return "Guinea";
            case "GW": return "Guinea-Bisáu";
            case "GY": return "Guyana";
            case "HT": return "Haití";
            case "HN": return "Honduras";
            case "HK": return "Hong Kong";
            case "HU": return "Hungría";
            case "IS": return "Islandia";
            case "IN": return "India";
            case "ID": return "Indonesia";
            case "IR": return "Irán";
            case "IQ": return "Irak";
            case "IE": return "Irlanda";
            case "IM": return "Isla de Man";
            case "IL": return "Israel";
            case "IT": return "Italia";
            case "JM": return "Jamaica";
            case "JP": return "Japón";
            case "JE": return "Jersey";
            case "JO": return "Jordania";
            case "KZ": return "Kazajistán";
            case "KE": return "Kenia";
            case "KI": return "Kiribati";
            case "XK": return "Kosovo";
            case "KW": return "Kuwait";
            case "KG": return "Kirguistán";
            case "LA": return "Laos";
            case "LV": return "Letonia";
            case "LB": return "Líbano";
            case "LS": return "Lesoto";
            case "LR": return "Liberia";
            case "LY": return "Libia";
            case "LI": return "Liechtenstein";
            case "LT": return "Lituania";
            case "LU": return "Luxemburgo";
            case "MO": return "Macao";
            case "MG": return "Madagascar";
            case "MW": return "Malaui";
            case "MY": return "Malasia";
            case "MV": return "Maldivas";
            case "ML": return "Malí";
            case "MT": return "Malta";
            case "MH": return "Islas Marshall";
            case "MQ": return "Martinica";
            case "MR": return "Mauritania";
            case "MU": return "Mauricio";
            case "YT": return "Mayotte";
            case "MX": return "México";
            case "FM": return "Micronesia";
            case "MD": return "Moldavia";
            case "MC": return "Mónaco";
            case "MN": return "Mongolia";
            case "ME": return "Montenegro";
            case "MS": return "Montserrat";
            case "MA": return "Marruecos";
            case "MZ": return "Mozambique";
            case "MM": return "Myanmar";
            case "NA": return "Namibia";
            case "NR": return "Nauru";
            case "NP": return "Nepal";
            case "NL": return "Países Bajos";
            case "NC": return "Nueva Caledonia";
            case "NZ": return "Nueva Zelanda";
            case "NI": return "Nicaragua";
            case "NE": return "Níger";
            case "NG": return "Nigeria";
            case "NU": return "Niue";
            case "KP": return "Corea del Norte";
            case "MK": return "Macedonia del Norte";
            case "MP": return "Islas Marianas del Norte";
            case "NO": return "Noruega";
            case "OM": return "Omán";
            case "PK": return "Pakistán";
            case "PW": return "Palaos";
            case "PS": return "Palestina";
            case "PA": return "Panamá";
            case "PG": return "Papúa Nueva Guinea";
            case "PY": return "Paraguay";
            case "PE": return "Perú";
            case "PH": return "Filipinas";
            case "PN": return "Islas Pitcairn";
            case "PL": return "Polonia";
            case "PT": return "Portugal";
            case "PR": return "Puerto Rico";
            case "QA": return "Catar";
            case "RE": return "Reunión";
            case "RO": return "Rumania";
            case "RU": return "Rusia";
            case "RW": return "Ruanda";
            case "BL": return "San Bartolomé";
            case "SH": return "Santa Helena";
            case "KN": return "San Cristóbal y Nieves";
            case "LC": return "Santa Lucía";
            case "MF": return "San Martín (parte francesa)";
            case "PM": return "San Pedro y Miquelón";
            case "VC": return "San Vicente y las Granadinas";
            case "WS": return "Samoa";
            case "SM": return "San Marino";
            case "ST": return "Santo Tomé y Príncipe";
            case "SA": return "Arabia Saudita";
            case "SN": return "Senegal";
            case "RS": return "Serbia";
            case "SC": return "Seychelles";
            case "SL": return "Sierra Leona";
            case "SG": return "Singapur";
            case "SX": return "Sint Maarten (parte holandesa)";
            case "SK": return "Eslovaquia";
            case "SI": return "Eslovenia";
            case "SB": return "Islas Salomón";
            case "SO": return "Somalia";
            case "ZA": return "Sudáfrica";
            case "KR": return "Corea del Sur";
            case "SS": return "Sudán del Sur";
            case "ES": return "España";
            case "LK": return "Sri Lanka";
            case "SD": return "Sudán";
            case "SR": return "Surinam";
            case "SJ": return "Svalbard y Jan Mayen";
            case "SE": return "Suecia";
            case "CH": return "Suiza";
            case "SY": return "Siria";
            case "TW": return "Taiwán";
            case "TJ": return "Tayikistán";
            case "TZ": return "Tanzania";
            case "TH": return "Tailandia";
            case "TL": return "Timor Oriental";
            case "TG": return "Togo";
            case "TK": return "Tokelau";
            case "TO": return "Tonga";
            case "TT": return "Trinidad y Tobago";
            case "TN": return "Túnez";
            case "TR": return "Turquía";
            case "TM": return "Turkmenistán";
            case "TC": return "Islas Turcas y Caicos";
            case "TV": return "Tuvalu";
            case "UG": return "Uganda";
            case "UA": return "Ucrania";
            case "AE": return "Emiratos Árabes Unidos";
            case "GB": return "Reino Unido";
            case "US": return "Estados Unidos";
            case "UY": return "Uruguay";
            case "UZ": return "Uzbekistán";
            case "VU": return "Vanuatu";
            case "VA": return "Ciudad del Vaticano";
            case "VE": return "Venezuela";
            case "VN": return "Vietnam";
            case "WF": return "Wallis y Futuna";
            case "EH": return "Sahara Occidental";
            case "YE": return "Yemen";
            case "ZM": return "Zambia";
            case "ZW": return "Zimbabue";
            default:
                return "País desconocido";
        }
    }
}
